### PR TITLE
Fix Package Renaming + Add Rename Command

### LINKED ISSUE #303: Discord module on Luna website does not behave well
### General Summary

Problem from the website, the discord widget does not behaves well when scrolling down

### Steps to Reproduce

Go to the luna website, scroll a bit, play with the discord module

### Actual Result

The discord module glitches and go behind one of the title : https://gfycat.com/ResponsibleForthrightCheetah

### PR DESCRIPTION
**Pull request by iamrecursion**
### Pull Request Description
This PR fixes #303, and the error reported in [luna-studio/#1025](https://github.com/luna/luna-studio/issues/1025). It also introduces a command-line `rename` command that utilises the same functionality. 

### Important Notes

- The bugfix changed a 'move' operation to a 'copy' operation to work across device boundaries. 
- The new command simply accepts a source and destination project name. 

### Checklist
Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] The code conforms to the [Luna Style Guide](https://github.com/luna/wiki/blob/master/code-style/01.general.md).
- [x] The code has been tested where possible.

### CODE REVIEW

File: package/src/Luna/Package.hs [hunk 1]
```diff
@@ -74,6 +77,9 @@ instance Exception RenameException where
     displayException (InaccessiblePath path) = show path <> " is inaccessible."
     displayException (InaccessibleFile file) = show file <> " is inaccessible."
     displayException (DestinationExists path) = show path <> " already exists."
+    displayException (CannotDelete path) = show path <> " already exists."
```
Comment (mikusp) [inline package/src/Luna/Package.hs]:
```suggestion
    displayException (CannotDelete path) = "Cannot delete " <> show path
```

File: package/src/Luna/Package.hs [hunk 2]
```diff
@@ -290,31 +301,61 @@ rename src target = Exception.rethrowFromIO @Path.PathException $ do
...
+    for_ dirsToCreate $ \dir -> do
+        let relPath = FilePath.makeRelative srcPath dir
+        liftIO . Directory.createDirectoryIfMissing True
+            $ destPath `FilePath.combine` relPath
+
+    for_ filesToCopy $ \file -> do
+        let relPath = FilePath.makeRelative srcPath file
+        liftIO . Directory.copyFile file $ destPath `FilePath.combine` relPath
+
+    Exception.catchAll (\(_ :: SomeException) ->
```
Comment (mikusp) [inline package/src/Luna/Package.hs]: I'll try to not discard exceptions, maybe add SomeException as a field to CannotDelete? It could contain valuable information about underlying cause

File: package/src/Luna/Package.hs [hunk 3]
```diff
@@ -290,31 +301,61 @@ rename src target = Exception.rethrowFromIO @Path.PathException $ do
...
     newName      <- name target
-    newProjFile  <- Path.parseRelFile $ convert newName <> Name.packageExt
+    newProjFile  <- Exception.rethrowFromIO @Path.PathException
+        . Path.parseRelFile $ convert newName <> Name.packageExt
 
     let origProjPath = target </> Name.configDirectory </> origProjFile
         newProjPath  = target </> Name.configDirectory </> newProjFile
 
-    liftIO $ Directory.renameFile (Path.fromAbsFile origProjPath)
+    Exception.catchAll (\(_ :: SomeException) ->
```
Comment (mikusp) [inline package/src/Luna/Package.hs]: Same here

File: shell/src/Luna/Shell/Command.hs [hunk 4]
```diff
@@ -228,6 +237,49 @@ version = putStrLn versionMsg where
...
+    canonicalSource <- getPath sourceDir
+    canonicalTarget <- getPath targetDir
+
+    resultPath <- Package.rename canonicalSource canonicalTarget
+
+    putStrLn $ "Package renamed to " <> Path.fromAbsDir resultPath
+
+    where
+        printRenameEx :: Package.RenameException -> m ()
+        printRenameEx e = liftIO . hPutStrLn stderr $ case e of
```
Comment (mikusp) [inline shell/src/Luna/Shell/Command.hs]: Use displayException?

File: shell/src/Luna/Shell/Command.hs [hunk 5]
```diff
@@ -228,6 +237,49 @@ version = putStrLn versionMsg where
...
+                <> " can't be found."
+            Package.DestinationExists path -> "Destination "
+                <> Path.fromAbsDir path <> " already exists."
+            Package.CannotDelete      path -> "Unable to delete "
+                <> Path.fromAbsDir path
+            Package.CannotRenameFile file -> "Cannot rename " <> show file
+
+        printPNFEx :: (MonadIO n, MonadException Package.RenameException n)
+            => Package.PackageNotFoundException -> n ()
+        printPNFEx e = liftIO . hPutStrLn stderr $ case e of
```
Comment (mikusp) [inline shell/src/Luna/Shell/Command.hs]: Use displayException?
